---
- name: Clean the environment
  block:
    - name: Remove any k3s configurations
      ansible.builtin.file:
        path: '{{ item }}'
        state: absent
      loop:
        - /var/lib/rancher
        - /etc/rancher
        - ~/.kube/*
    
    - name: Flush network configurations
      ansible.builtin.shell:
        cmd: |
          ip addr flush dev lo;
          ip addr add 127.0.0.1/8 dev lo;

- name: Copy kube-vip additional manifests
  block:
    - name: Make manifests directory
      ansible.builtin.file:
        path: "/var/lib/rancher/k3s/server/manifests"
        mode: 0700
        state: directory

    - name: Copy kube-vip daemonset manifest
      ansible.builtin.template:
        src: "kube-vip-daemonset.yaml.j2"
        dest: "/var/lib/rancher/k3s/server/manifests/kube-vip-daemonset.yaml"
        mode: 0600

    - name: Download static kube-vip manifests
      block:
        - name: Download kube-vip rbac manifest
          ansible.builtin.get_url:
            url: https://kube-vip.io/manifests/rbac.yaml
            timeout: 60
            dest: "/var/lib/rancher/k3s/server/manifests/kube-vip-rbac.yaml"
            mode: 0600 

        - name: Download kube-vip cloud provider manifest
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml
            timeout: 60
            dest: "/var/lib/rancher/k3s/server/manifests/kube-vip-cloud-provider.yaml"
            mode: 0600 
